
/* AUTO-GENERATED by gen_isr_tables.py, do not edit! */

#include <zephyr/toolchain.h>
#include <zephyr/linker/sections.h>
#include <zephyr/sw_isr_table.h>
#include <zephyr/arch/cpu.h>

_Z_ISR_TABLE_ENTRY(0, z_irq_spurious, NULL, ".isr_generated.0x0");
_Z_ISR_TABLE_ENTRY(1, z_irq_spurious, NULL, ".isr_generated.0x1");
_Z_ISR_TABLE_ENTRY(2, z_irq_spurious, NULL, ".isr_generated.0x2");
_Z_ISR_TABLE_ENTRY(3, z_irq_spurious, NULL, ".isr_generated.0x3");
_Z_ISR_TABLE_ENTRY(4, z_irq_spurious, NULL, ".isr_generated.0x4");
_Z_ISR_TABLE_ENTRY(5, z_irq_spurious, NULL, ".isr_generated.0x5");
_Z_ISR_TABLE_ENTRY(6, z_irq_spurious, NULL, ".isr_generated.0x6");
_Z_ISR_TABLE_ENTRY(7, z_irq_spurious, NULL, ".isr_generated.0x7");
_Z_ISR_TABLE_ENTRY(8, z_irq_spurious, NULL, ".isr_generated.0x8");
_Z_ISR_TABLE_ENTRY(9, z_irq_spurious, NULL, ".isr_generated.0x9");
_Z_ISR_TABLE_ENTRY(10, z_irq_spurious, NULL, ".isr_generated.0xa");
_Z_ISR_TABLE_ENTRY(11, z_irq_spurious, NULL, ".isr_generated.0xb");
_Z_ISR_TABLE_ENTRY(12, z_irq_spurious, NULL, ".isr_generated.0xc");
_Z_ISR_TABLE_ENTRY(13, z_irq_spurious, NULL, ".isr_generated.0xd");
_Z_ISR_TABLE_ENTRY(14, z_irq_spurious, NULL, ".isr_generated.0xe");
_Z_ISR_TABLE_ENTRY(15, z_irq_spurious, NULL, ".isr_generated.0xf");
_Z_ISR_TABLE_ENTRY(16, z_irq_spurious, NULL, ".isr_generated.0x10");
_Z_ISR_TABLE_ENTRY(17, z_irq_spurious, NULL, ".isr_generated.0x11");
_Z_ISR_TABLE_ENTRY(18, z_irq_spurious, NULL, ".isr_generated.0x12");
_Z_ISR_TABLE_ENTRY(19, z_irq_spurious, NULL, ".isr_generated.0x13");
_Z_ISR_TABLE_ENTRY(20, z_irq_spurious, NULL, ".isr_generated.0x14");
_Z_ISR_TABLE_ENTRY(21, z_irq_spurious, NULL, ".isr_generated.0x15");
_Z_ISR_TABLE_ENTRY(22, z_irq_spurious, NULL, ".isr_generated.0x16");
_Z_ISR_TABLE_ENTRY(23, z_irq_spurious, NULL, ".isr_generated.0x17");
_Z_ISR_TABLE_ENTRY(24, z_irq_spurious, NULL, ".isr_generated.0x18");
_Z_ISR_TABLE_ENTRY(25, z_irq_spurious, NULL, ".isr_generated.0x19");
_Z_ISR_TABLE_ENTRY(26, z_irq_spurious, NULL, ".isr_generated.0x1a");
_Z_ISR_TABLE_ENTRY(27, z_irq_spurious, NULL, ".isr_generated.0x1b");
_Z_ISR_TABLE_ENTRY(28, z_irq_spurious, NULL, ".isr_generated.0x1c");
_Z_ISR_TABLE_ENTRY(29, z_irq_spurious, NULL, ".isr_generated.0x1d");
_Z_ISR_TABLE_ENTRY(30, z_irq_spurious, NULL, ".isr_generated.0x1e");
_Z_ISR_TABLE_ENTRY(31, z_irq_spurious, NULL, ".isr_generated.0x1f");
_Z_ISR_TABLE_ENTRY(32, z_irq_spurious, NULL, ".isr_generated.0x20");
_Z_ISR_TABLE_ENTRY(33, z_irq_spurious, NULL, ".isr_generated.0x21");
_Z_ISR_TABLE_ENTRY(34, z_irq_spurious, NULL, ".isr_generated.0x22");
_Z_ISR_TABLE_ENTRY(35, z_irq_spurious, NULL, ".isr_generated.0x23");
_Z_ISR_TABLE_ENTRY(36, z_irq_spurious, NULL, ".isr_generated.0x24");
_Z_ISR_TABLE_ENTRY(37, z_irq_spurious, NULL, ".isr_generated.0x25");
_Z_ISR_TABLE_ENTRY(38, z_irq_spurious, NULL, ".isr_generated.0x26");
_Z_ISR_TABLE_ENTRY(39, z_irq_spurious, NULL, ".isr_generated.0x27");
_Z_ISR_TABLE_ENTRY(40, z_irq_spurious, NULL, ".isr_generated.0x28");
_Z_ISR_TABLE_ENTRY(41, z_irq_spurious, NULL, ".isr_generated.0x29");
_Z_ISR_TABLE_ENTRY(42, z_irq_spurious, NULL, ".isr_generated.0x2a");
_Z_ISR_TABLE_ENTRY(43, z_irq_spurious, NULL, ".isr_generated.0x2b");
_Z_ISR_TABLE_ENTRY(44, z_irq_spurious, NULL, ".isr_generated.0x2c");
_Z_ISR_TABLE_ENTRY(45, z_irq_spurious, NULL, ".isr_generated.0x2d");
_Z_ISR_TABLE_ENTRY(46, z_irq_spurious, NULL, ".isr_generated.0x2e");
_Z_ISR_TABLE_ENTRY(47, z_irq_spurious, NULL, ".isr_generated.0x2f");
