# Enable nRF Desktop
CONFIG_DESKTOP_ROLE_HID_PERIPHERAL=y

# Use Mouse as the peripheral type
CONFIG_DESKTOP_PERIPHERAL_TYPE_MOUSE=y

# Enable USB
CONFIG_DESKTOP_USB_ENABLE=y

# Enable BLE
CONFIG_DESKTOP_BT=y

# Enable buttons
CONFIG_CAF_BUTTONS=y
CONFIG_CAF_BUTTONS_POLARITY_INVERSED=y

# Use buttons for motion
CONFIG_DESKTOP_MOTION_BUTTONS_ENABLE=n
# CONFIG_DESKTOP_MOTION_BUTTONS_UP_KEY_ID=0
# CONFIG_DESKTOP_MOTION_BUTTONS_DOWN_KEY_ID=1
# CONFIG_DESKTOP_MOTION_BUTTONS_LEFT_KEY_ID=2
# CONFIG_DESKTOP_MOTION_BUTTONS_RIGHT_KEY_ID=3

# Enable SPI
CONFIG_SPI=y

# Enable PMW3389 sensor
CONFIG_PMW3389=y
CONFIG_PMW3389_TRIGGER_GLOBAL_THREAD=y
CONFIG_PMW3389_CPI=1600


# Settings
CONFIG_SETTINGS=y
CONFIG_BT_ID_MAX=4

################################################################################
# Zephyr Configuration

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_ISR_STACK_SIZE=1536
CONFIG_MAIN_STACK_SIZE=840
CONFIG_BT_RX_STACK_SIZE=2048
CONFIG_BT_HCI_TX_STACK_SIZE_WITH_PROMPT=y
CONFIG_BT_HCI_TX_STACK_SIZE=1536

CONFIG_HEAP_MEM_POOL_SIZE=1024

CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
CONFIG_SYSTEM_CLOCK_NO_WAIT=y

CONFIG_RESET_ON_FATAL_ERROR=n

CONFIG_GPIO=y
CONFIG_REBOOT=y

CONFIG_SPEED_OPTIMIZATIONS=y

CONFIG_BT_MAX_PAIRED=5

CONFIG_FW_INFO=y
CONFIG_FW_INFO_FIRMWARE_VERSION=1